// Code generated by "stringer -type=Event"; DO NOT EDIT.

package stewdy

import "strconv"

const _Event_name = "OriginateAnswerConnectFail"

var _Event_index = [...]uint8{0, 9, 15, 22, 26}

func (i Event) String() string {
	i -= 1
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
